In [92]:
import numpy as np
import pandas as pd

In [93]:
n = 10
p = 2
x0 = np.ones(n)
x1 = np.random.normal(20,1,n)
x2 = np.random.normal(30,1,n)

In [94]:
X = np.column_stack((x0,x1,x2))
X

array([[ 1.        , 20.54886168, 31.85708788],
       [ 1.        , 20.06707765, 29.01526243],
       [ 1.        , 19.92715072, 29.90118435],
       [ 1.        , 20.5516735 , 29.68163574],
       [ 1.        , 21.34839285, 30.28737207],
       [ 1.        , 20.24070868, 29.78233854],
       [ 1.        , 19.53514153, 28.85449422],
       [ 1.        , 21.54906973, 30.28215348],
       [ 1.        , 20.84176568, 28.75399522],
       [ 1.        , 20.41802496, 32.03452026]])

In [95]:
b = np.arange(1,3+1)
b.reshape(3,1)
b.shape

(3,)

In [98]:
y =  X @ b
y

array([137.668987  , 128.17994261, 130.55785447, 131.14825422,
       134.55890192, 130.82843297, 126.63376572, 134.94459992,
       128.94551703, 137.9396107 ])

In [102]:
np.linalg.inv(X.transpose() @ X) @ X.transpose() @ y

array([1., 2., 3.])

In [104]:
def ClosedFormLinRegNumpy(X,y):
    return np.linalg.inv(X.transpose() @ X) @ X.transpose() @ y

In [105]:
ClosedFormLinRegNumpy(X,y)

array([1., 2., 3.])